version: "3.8"
services:
  nginx:
    image: nginx:1.18.0
    ports:
      - "80:80"
      - "10002:80"
    volumes:
      - "./server/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./server/nginx/conf.d:/etc/nginx/conf.d"
      - "./runtime/nginx/log:/var/log/nginx"
      - ".:/usr/share/nginx/html"
  php:
    build:
      context: ./server/php
    volumes:
      - "./server/php/php.ini:/usr/local/etc/php/php.ini"
      - "./server/php/php-fpm.conf:/usr/local/etc/php-fpm.conf"
      - "./server/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf"
      - ".:/usr/share/nginx/html"
    command: sh -c "/bin/sh /usr/share/nginx/html/run.test.sh"
    # command: sh -c "php-fpm -R"
  mysql:
    image: mysql:8.0.23
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - "./runtime/mysql/data:/var/lib/mysql"
      - "./server/mysql/conf:/etc/mysql/conf.d"
  redis:
    image: redis:5.0.9
    # ports:
    #   - "6379:6379"
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:
      - "./runtime/redis/data/:/data/"
  mongo_local:
    image: mongo:5.0.6
    volumes:
      - "mongo:/data/db"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    tty: true
  consul:
    image: consul:1.8.3
    ports:
      - "8500:8500"
  minio:
    image: minio/minio:latest                                    # 原镜像`minio/minio:latest`
    volumes: # 数据卷挂载路径设置,将本机目录映射到容器目录
      - "./runtime/minio/data:/minioData"
      - "./runtime/minio/minio:/minio"
      - "./runtime/minio/config:/root/.minio"
    environment: # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
      MINIO_ROOT_USER: "root"                        # 登录账号
      MINIO_ROOT_PASSWORD: "password"                    # 登录密码
    command: server /minioData --console-address ":9001"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    ports: # 映射端口
      - "9000:9000"
      - "9001:9001"


volumes:
    mongo:

networks:
  default:
    name: nikash-network
